name: "Copy .npmrc File"
description: "Create .npmrc file for GitHub (.npmrc.github)"
runs:
  using: composite
  steps:
    - run: mv .npmrc .npmrc_old
      shell: bash

    - run: cp .npmrc.github .npmrc
      shell: bash
