name: Licence Manager
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  license-manager:
    name: License Manager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.SUBMODULES }}
          submodules: recursive
      - name: Execute Fossa
        run: |
          ./submodules/jenkins-util/workflows/fossa-check-runs
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
